name: Test Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    
    steps:
    - name: Simple Test
      run: |
        echo "Hello from runner!"
        pwd
        dir